# Generated by Django 5.0.6 on 2024-05-31 11:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AWSStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_id", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("curr_rainfall", models.FloatField(default=0)),
                ("curr_temp", models.FloatField(default=0)),
                (
                    "arr_rainfall",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=30
                    ),
                ),
                (
                    "arr_temp",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=30
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "pred_rainfall",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=5
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="awsstations.awsstation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HourlyPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "pred_rainfall",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=25
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="awsstations.awsstation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rainfall", models.FloatField(default=0)),
                ("temperature", models.FloatField(default=0)),
                ("humidity", models.FloatField(default=0)),
                ("windSpeed", models.FloatField(default=0)),
                ("timestamp", models.DateTimeField()),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="awsstations.awsstation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_name", models.CharField(max_length=100)),
                ("station_code", models.CharField(max_length=10)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("WarningLevel", models.IntegerField(default=0)),
                (
                    "rainfall",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=10
                    ),
                ),
                (
                    "neareststation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="awsstations.trainstation",
                    ),
                ),
            ],
        ),
    ]
