# Generated by Django 5.0.6 on 2024-06-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awsstations", "0002_alter_trainstation_neareststation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainstation",
            name="id",
        ),
        migrations.AlterField(
            model_name="trainstation",
            name="station_code",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
