# Generated by Django 5.0.6 on 2024-06-01 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("awsstations", "0004_awsstation_curr_windspeed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stationdata",
            old_name="windSpeed",
            new_name="wind_speed",
        ),
    ]
