# Generated by Django 5.0.6 on 2024-06-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awsstations", "0005_rename_windspeed_stationdata_wind_speed"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyprediction",
            name="day",
            field=models.IntegerField(
                choices=[(1, "Day 1"), (2, "Day 2"), (3, "Day 3")], default=1
            ),
        ),
    ]
