# Generated by Django 5.0.6 on 2024-06-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awsstations", "0006_dailyprediction_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyprediction",
            name="pred_rainfall",
            field=models.FloatField(default=0),
        ),
    ]
